### ISSUE TITLE
Best location for classes

### ISSUE THREAD

**Issue by joshua1** [CodeAdventure/meteor-class#1]
@DominikGuzei what is the best locations for classes. is it the lib or server folder?

**Comment by DominikGuzei** [comment]
@joshua1 what do you mean? Classes are a basic programming construct you can use anywhere. This library just simplifies working with classical inheritance in Javascript similar to how Coffeescript does.

Where you put your code depends on how you want to structure the overall application, that's pretty much a matter of taste or conventions. E.g: I never use a `lib` folder and also don't think it's a great naming convention because it's way to general and just shows that you have no clear idea about this code.
